### ISSUE TITLE
test the response body 

### ISSUE THREAD

**Issue by abdhalees** [FACG2/getGitHub#37]
All your tests are just checking the response status code, you also could test the response body, even if the information itself might change on every request you could check for other things e.g. type of body, if it's an array check the length of it. 
in https://github.com/FACG2/getGitHub/blob/master/test/back-end-test.js#L13 you could also test that your request responses with the right username or the the response has an object that contains "your repos"

**Comment by SamerElaila** [comment]
Done :smile:
